package com.expensetracker.app.presentation.theme

import androidx.compose.ui.graphics.Color

val GreenPrimary = Color(0xFF2E7D32)
val GreenPrimaryDark = Color(0xFF81C995)
val GreenSecondary = Color(0xFF558B2F)
val IncomeGreen = Color(0xFF2E7D32)
val ExpenseRed = Color(0xFFC62828)

val md_theme_light_primary = Color(0xFF2E7D32)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA8F5A2)
val md_theme_light_onPrimaryContainer = Color(0xFF002106)
val md_theme_light_secondary = Color(0xFF53634F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD6E8CF)
val md_theme_light_onSecondaryContainer = Color(0xFF121F0F)
val md_theme_light_background = Color(0xFFFCFDF6)
val md_theme_light_onBackground = Color(0xFF1A1C18)
val md_theme_light_surface = Color(0xFFFCFDF6)
val md_theme_light_onSurface = Color(0xFF1A1C18)
val md_theme_light_surfaceVariant = Color(0xFFDFE4D7)
val md_theme_light_onSurfaceVariant = Color(0xFF43483F)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_outline = Color(0xFF73796E)

val md_theme_dark_primary = Color(0xFF8DD98A)
val md_theme_dark_onPrimary = Color(0xFF00390A)
val md_theme_dark_primaryContainer = Color(0xFF005313)
val md_theme_dark_onPrimaryContainer = Color(0xFFA8F5A2)
val md_theme_dark_secondary = Color(0xFFBACCB3)
val md_theme_dark_onSecondary = Color(0xFF263422)
val md_theme_dark_secondaryContainer = Color(0xFF3C4B37)
val md_theme_dark_onSecondaryContainer = Color(0xFFD6E8CF)
val md_theme_dark_background = Color(0xFF1A1C18)
val md_theme_dark_onBackground = Color(0xFFE2E3DC)
val md_theme_dark_surface = Color(0xFF1A1C18)
val md_theme_dark_onSurface = Color(0xFFE2E3DC)
val md_theme_dark_surfaceVariant = Color(0xFF43483F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C8BB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_outline = Color(0xFF8D9388)
